# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirshipSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AirshipTabbedExample
  pod "TealiumIOS"
  pod "TealiumIOSLifecycle"
  pod "Airship"
  pod "Airship/Location"
end
